import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

/*
  `next lint` is removed in Next 16 and, with no config present, drops into an
  interactive setup prompt instead of linting — which meant `npm run lint`
  could never run in CI. This is the ESLint CLI with Next's own rules.

  Formatting is Prettier's job, not ESLint's, so no stylistic rules live here.
*/
const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "coverage/**",
      // Generated by drizzle-kit.
      "src/db/migrations/**",
      // Written by Next on every build; its triple-slash refs are not ours.
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // The codebase uses `void promise` deliberately to mark fire-and-forget
      // work (analytics, revision writes) that must not block a response.
      "@typescript-eslint/no-floating-promises": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
];

export default config;
